// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SharedModel.Models;


[JsonSerializable(typeof(ChatUser))]
public partial class ChatUser
{
    public int ChatUserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public byte[] AvatarImage { get; set; }

    public bool? IsLoggedIn { get; set; }
}