// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SharedModel.Models;

public partial class FlameChatContext : DbContext
{
    public FlameChatContext(DbContextOptions<FlameChatContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdminUser> AdminUsers { get; set; }

    public virtual DbSet<ChatUser> ChatUsers { get; set; }

    public virtual DbSet<MasterAdminPassword> MasterAdminPasswords { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<NotifiedMessage> NotifiedMessages { get; set; }

    public virtual DbSet<PersonalityTrait> PersonalityTraits { get; set; }

    public virtual DbSet<ReceivedMessage> ReceivedMessages { get; set; }

    public virtual DbSet<SeenMessage> SeenMessages { get; set; }

    public virtual DbSet<SentMessage> SentMessages { get; set; }

    public virtual DbSet<UserHasContact> UserHasContacts { get; set; }

    public virtual DbSet<UserHasTrait> UserHasTraits { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdminUser>(entity =>
        {
            entity.ToTable("AdminUser");

            entity.Property(e => e.AdminUserId).HasColumnName("AdminUserID");
            entity.Property(e => e.Password).HasMaxLength(500);
            entity.Property(e => e.Username).HasMaxLength(500);
        });

        modelBuilder.Entity<ChatUser>(entity =>
        {
            entity.HasKey(e => e.ChatUserId).HasName("PK__MessageU__4F4D834240D28D1B");

            entity.ToTable("ChatUser");

            entity.Property(e => e.ChatUserId).HasColumnName("ChatUserID");
            entity.Property(e => e.Password).HasMaxLength(500);
            entity.Property(e => e.Username).HasMaxLength(500);
        });

        modelBuilder.Entity<MasterAdminPassword>(entity =>
        {
            entity.ToTable("MasterAdminPassword");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.MasterAdminPassword1)
                .HasMaxLength(500)
                .HasColumnName("MasterAdminPassword");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Message__C87C037CE6E9AA2E");

            entity.ToTable("Message");

            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.DateTimeOfSending).HasColumnType("datetime");
            entity.Property(e => e.FkUserWhoSentId).HasColumnName("FK_UserWhoSentID");
            entity.Property(e => e.FkWhoReceivedId).HasColumnName("FK_WhoReceivedID");
            entity.Property(e => e.Text).HasMaxLength(1000);
        });

        modelBuilder.Entity<NotifiedMessage>(entity =>
        {
            entity.HasKey(e => e.NotifiedMessageId).HasName("PK__Notified__7D005A77BB02490E");

            entity.Property(e => e.NotifiedMessageId).HasColumnName("NotifiedMessageID");
            entity.Property(e => e.CkMessageId).HasColumnName("CK_MessageID");
            entity.Property(e => e.CkUserNotifiedId).HasColumnName("CK_UserNotifiedID");
        });

        modelBuilder.Entity<PersonalityTrait>(entity =>
        {
            entity.HasKey(e => e.PersonalityTraitId).HasName("PK__Personal__0BFA7AF6BACEFE4A");

            entity.Property(e => e.PersonalityTraitId).HasColumnName("PersonalityTraitID");
            entity.Property(e => e.TraitName).HasMaxLength(100);
        });

        modelBuilder.Entity<ReceivedMessage>(entity =>
        {
            entity.HasKey(e => e.ReceivedMessageId).HasName("PK__Received__90EC8CC6D6248DCF");

            entity.Property(e => e.ReceivedMessageId).HasColumnName("ReceivedMessageID");
            entity.Property(e => e.CkMessageId).HasColumnName("CK_MessageID");
            entity.Property(e => e.CkUserReceivedId).HasColumnName("CK_UserReceivedID");
        });

        modelBuilder.Entity<SeenMessage>(entity =>
        {
            entity.HasKey(e => e.SeenMessageId).HasName("PK__SeenMess__37A68C96DD606ED9");

            entity.Property(e => e.SeenMessageId).HasColumnName("SeenMessageID");
            entity.Property(e => e.CkMessageId).HasColumnName("CK_MessageID");
            entity.Property(e => e.CkUserSeenId).HasColumnName("CK_UserSeenID");
        });

        modelBuilder.Entity<SentMessage>(entity =>
        {
            entity.HasKey(e => e.SentMessageId).HasName("PK__SentMess__236E323B18BB6419");

            entity.Property(e => e.SentMessageId).HasColumnName("SentMessageID");
            entity.Property(e => e.CkMessageId).HasColumnName("CK_MessageID");
            entity.Property(e => e.CkUserSentId).HasColumnName("CK_UserSentID");
        });

        modelBuilder.Entity<UserHasContact>(entity =>
        {
            entity.HasKey(e => e.UserHasContactId).HasName("PK__UserHasC__5C6625BBB14942FC");

            entity.ToTable("UserHasContact");

            entity.Property(e => e.UserHasContactId).HasColumnName("UserHasContactID");
            entity.Property(e => e.UserContactId).HasColumnName("UserContactID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<UserHasTrait>(entity =>
        {
            entity.HasKey(e => e.UserHasTraitId).HasName("PK__UserHasT__A0E9F47B7D701C27");

            entity.Property(e => e.UserHasTraitId).HasColumnName("UserHasTraitID");
            entity.Property(e => e.CkChatUserId).HasColumnName("CK_ChatUserID");
            entity.Property(e => e.CkPersonalityTraitId).HasColumnName("CK_PersonalityTraitID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}