// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SharedModel.Models;

public partial class MasterAdminPassword
{
    public int Id { get; set; }

    public string MasterAdminPassword1 { get; set; }
}