// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SharedModel.Models;

[JsonSerializable(typeof(Message))]
public partial class Message
{
    public int MessageId { get; set; }

    public string Text { get; set; }

    public DateTime? DateTimeOfSending { get; set; }

    public int? FkUserWhoSentId { get; set; }

    public int? FkWhoReceivedId { get; set; }
}