// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SharedModel.Models;

[JsonSerializable(typeof(NotifiedMessage))]
public partial class NotifiedMessage
{
    public int NotifiedMessageId { get; set; }

    public int? CkUserNotifiedId { get; set; }

    public int? CkMessageId { get; set; }
}