// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SharedModel.Models;

[JsonSerializable(typeof(PersonalityTrait))]
public partial class PersonalityTrait
{
    public int PersonalityTraitId { get; set; }

    public string TraitName { get; set; }
}