// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SharedModel.Models;

[JsonSerializable(typeof(ReceivedMessage))]
public partial class ReceivedMessage
{
    public int ReceivedMessageId { get; set; }

    public int? CkUserReceivedId { get; set; }

    public int? CkMessageId { get; set; }
}