// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SharedModel.Models;

[JsonSerializable(typeof(SeenMessage))]
public partial class SeenMessage
{
    public int SeenMessageId { get; set; }

    public int? CkUserSeenId { get; set; }

    public int? CkMessageId { get; set; }
}