// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SharedModel.Models;

[JsonSerializable(typeof(SentMessage))]
public partial class SentMessage
{
    public int SentMessageId { get; set; }

    public int? CkUserSentId { get; set; }

    public int? CkMessageId { get; set; }
}