// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SharedModel.Models;

[JsonSerializable(typeof(UserHasTrait))]
public partial class UserHasTrait
{
    public int UserHasTraitId { get; set; }

    public int? CkChatUserId { get; set; }

    public int? CkPersonalityTraitId { get; set; }
}