// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SharedModel.Models;

[JsonSerializable(typeof(UserHasContact))]
public partial class UserHasContact
{
    public int UserHasContactId { get; set; }

    public int? UserId { get; set; }

    public int? UserContactId { get; set; }
}